/**
 * @fileoverview API response and request payload types (e.g. candidate from backend).
 */

/**
 * Base candidate shape from API (may differ from dashboard ExtendedCandidate).
 */
export interface Candidate {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  cvUrl: string;
  overallScore?: number;
  evaluationResults?: unknown;
}

/** Parsed CV preview returned after uploading a CV. */
export interface ParsedCv {
  experienceLevel?: string;
  detectedStack?: string[];
  sections?: Record<string, string>;
}

/** Upload CV response, includes parsed data preview and optional R2 storage key. */
export interface UploadCvResponse {
  /** Unique candidate UUID generated by the backend. */
  candidateId: string;
  /** R2 object key where the raw PDF was stored (e.g. "cvs/uuid.pdf"). */
  r2Key?: string;
  /** Structured CV preview parsed by Gemini (experienceLevel, detectedStack, sections). */
  parsed?: ParsedCv;
}

/** Answer submission for candidate evaluation. */
export interface CandidateAnswerPayload {
  questionId: string;
  answerText: string;
}

/** Validate-invitation API response. */
export interface ValidateInvitationResponse {
  valid: boolean;
  message?: string;
  candidateEmail?: string;
  candidateName?: string;
  jobTitle?: string;
  organizationId?: string;
  jobId?: string;
}
